
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { Download, Share2, BellRing, Info } from 'lucide-react';
import type { DailyAnalytics } from '@/services/firestore-service';

interface AiSummaryCardProps {
    summaryData: DailyAnalytics | undefined;
}

export function AiSummaryCard({ summaryData }: AiSummaryCardProps) {
    // In a real app, this would be generated by an AI flow.
    const getSummaryText = () => {
        if (!summaryData || summaryData.total_messages === 0) {
            return "No activity recorded for this day.";
        }
        const topCategory = Object.entries(summaryData.by_category || {}).sort((a,b) => b[1] - a[1])[0]?.[0];

        return `You sent ${summaryData.total_messages} messages today. Your most used category was '${topCategory || 'General'}'. The average AI response time was ${summaryData.avg_latency_ms}ms. Keep up the great work!`;
    }
    
    return (
        <Card>
            <CardHeader>
                <CardTitle>AI-Generated Summary</CardTitle>
                <CardDescription>A summary of the day's key activities and insights.</CardDescription>
            </CardHeader>
            <CardContent>
                {summaryData ? (
                    <p className="text-sm leading-relaxed">{getSummaryText()}</p>
                ): (
                    <div className="flex items-center gap-2 text-muted-foreground">
                        <Info className="h-4 w-4" />
                        <p>No data available for the selected date.</p>
                    </div>
                )}
            </CardContent>
            <CardFooter className="gap-2">
                <Button variant="outline"><Download className="mr-2 h-4 w-4" /> Export as PDF</Button>
                <Button variant="outline"><Share2 className="mr-2 h-4 w-4" /> Share with Team</Button>
                <Button variant="outline"><BellRing className="mr-2 h-4 w-4" /> Schedule Daily Email</Button>
            </CardFooter>
        </Card>
    );
}

export function AiSummaryCardSkeleton() {
    return (
        <Card>
            <CardHeader>
                <Skeleton className="h-6 w-1/2" />
                <Skeleton className="h-4 w-3/4 mt-2" />
            </CardHeader>
            <CardContent className="space-y-2">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-2/3" />
            </CardContent>
            <CardFooter className="gap-2">
                <Skeleton className="h-10 w-32" />
                <Skeleton className="h-10 w-32" />
                <Skeleton className="h-10 w-36" />
            </CardFooter>
        </Card>
    );
}
